import {collect} from '../collect.js';
import type {Run} from '../types.js';
const marker='omni-poc-host';
if(!document.getElementById(marker))boot();
function boot(){
  const host=document.createElement('div');host.id=marker;host.style.cssText='position:fixed;right:16px;bottom:16px;z-index:2147483647';const root=host.attachShadow({mode:'open'});
  const style=document.createElement('style');style.textContent=':host{all:initial}section{font:13px system-ui;background:#101c2d;color:#f3f7ff;border:1px solid #4e7098;border-radius:10px;width:350px;padding:14px;box-shadow:0 5px 25px #0006;max-height:75vh;overflow:auto}h3{margin:0 0 8px;font-size:16px}button{padding:6px;margin:3px}a{color:#8bceff;display:block;margin:7px 0}pre{white-space:pre-wrap;word-break:break-all;font:11px monospace}details{padding:6px 0;border-top:1px solid #456}p{margin:8px 0}';root.append(style);
  const box=document.createElement('section');const title=document.createElement('h3');title.textContent='Omni 상품 탐색 PoC';const status=document.createElement('p');const result=document.createElement('div');const refresh=document.createElement('button');refresh.textContent='다시 분석';const debugButton=document.createElement('button');debugButton.textContent='DEBUG Panel';const stop=document.createElement('button');stop.textContent='중지';const debug=document.createElement('div');debug.hidden=true;box.append(title,status,refresh,debugButton,stop,result,debug);root.append(box);document.documentElement.append(host);
  let stopped=false,busy=false,previous=location.href,lastRun:Run|null=null;let scheduled:ReturnType<typeof setTimeout>|undefined;
  debugButton.onclick=()=>{debug.hidden=!debug.hidden;};
  function render(run:Run){const t=performance.now();lastRun=run;status.textContent=`${run.status} · 캡처 ${run.capture.performed?'실행':run.capture.capture?'대기/실패':'안 함'}`;result.replaceChildren();const current=document.createElement('p');current.textContent=run.extracted.product?`${run.extracted.product.name} / ${run.extracted.product.price??'가격 미확인'} ${run.extracted.product.currency}`:run.capture.reason.join(', ');result.append(current);
    for(const p of run.results.slice(0,5)){const a=document.createElement('a');a.href=p.product_url;a.target='_blank';a.rel='noopener noreferrer';const cheaper=p.match==='same'&&p.price_comparable&&p.price!==null&&p.price<(run.extracted.product?.price??0);a.textContent=`${cheaper?'더 저렴함 · ':''}${p.name} · ${p.price??'?'} ${p.currency} · ${p.source_site} · ${p.match==='same'?'동일 후보':'유사 상품'}`;a.title=p.reasons.join(' / ');result.append(a);}
    debug.replaceChildren();for(const key of ['raw','capture','extracted','classification','queries','providers','results','storage','discarded','resources','timings','logs'] as const){const d=document.createElement('details');const s=document.createElement('summary');s.textContent=key.toUpperCase();const pre=document.createElement('pre');pre.textContent=JSON.stringify(run[key],null,2);d.append(s,pre);debug.append(d);}run.timings.render_latency=performance.now()-t;host.dataset.status=run.status;host.dataset.session=run.session_id;
  }
  async function analyze(){if(stopped||busy||document.visibilityState!=='visible')return;busy=true;status.textContent='페이지 분석 중';const t=performance.now();
    try{const raw=collect(document,location.href);if(!raw.signals.product&&!raw.signals.price&&!raw.signals.sensitive){await new Promise(r=>setTimeout(r,800));Object.assign(raw,collect(document,location.href));}
      host.style.visibility='hidden';await new Promise(requestAnimationFrame);const response=await chrome.runtime.sendMessage({type:'ANALYZE',raw});host.style.visibility='visible';if(response.error)throw new Error(response.error);
      const deadline=Date.now()+90000;while(Date.now()<deadline&&!stopped){const run=await chrome.runtime.sendMessage({type:'POLL',id:response.session_id});if(run.error)throw new Error(run.error);render(run);if(['complete','complete_no_results','skipped','error','no_product'].includes(run.status)){run.timings.client_total_latency=performance.now()-t;await chrome.runtime.sendMessage({type:'METRICS',id:run.session_id,render_ms:run.timings.render_latency,client_total_ms:run.timings.client_total_latency});render(run);return;}await new Promise(r=>setTimeout(r,500));}if(!stopped)throw new Error('PIPELINE_TIMEOUT');
    }catch(e){status.textContent=`분석 오류: ${String(e)} — 서버/토큰 확인 후 다시 분석`;host.dataset.status='error';}finally{host.style.visibility='visible';busy=false;}}
  refresh.onclick=()=>void analyze();
  const nav=setInterval(()=>{if(location.href!==previous){previous=location.href;void analyze();}},1000);
  const observer=new MutationObserver(m=>{if(stopped||busy||!lastRun||lastRun.status==='complete'||m.every(x=>host.contains(x.target)||x.target===host))return;clearTimeout(scheduled);scheduled=setTimeout(()=>void analyze(),3000);});observer.observe(document.body,{childList:true,subtree:true});
  const shutdown=()=>{stopped=true;clearInterval(nav);clearTimeout(scheduled);observer.disconnect();host.remove();lastRun=null;};stop.onclick=shutdown;chrome.runtime.onMessage.addListener(m=>{if(m.type==='STOP')shutdown();});setTimeout(()=>{if(lastRun){debug.replaceChildren();lastRun=null;}},600000);void analyze();
}
