import {chromium} from 'playwright';
import {parseHTML} from 'linkedom';
import os from 'node:os';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {collect} from '../src/collect.js';
import {decide,extract,similarity,stats} from '../src/core.js';
import {createRun,processRun,eraseAll} from '../src/pipeline.js';
import {runOcr} from '../src/ocr.js';
import {cases,productHtml} from '../tests/fixtures.js';
import type {Product,Run} from '../src/types.js';
const raw=(html:string,url='https://merchant.example/product/buds')=>collect(parseHTML(html).document as unknown as Document,url);
const accuracy:Record<string,any>={};const predictions=cases.map(f=>{const r=raw(f.html,f.url);return {id:f.id,truth:f,prediction:{capture:decide(r).capture,product:extract(r)}};});
const binary=(truth:boolean[],pred:boolean[])=>{let tp=0,tn=0,fp=0,fn=0;truth.forEach((t,i)=>{if(t&&pred[i])tp++;else if(!t&&!pred[i])tn++;else if(!t&&pred[i])fp++;else fn++;});const precision=tp/(tp+fp||1),recall=tp/(tp+fn||1);return {n:truth.length,tp,tn,fp,fn,accuracy:(tp+tn)/truth.length,precision,recall,f1:2*precision*recall/(precision+recall||1)};};
accuracy.capture=binary(cases.map(f=>f.capture),predictions.map(p=>p.prediction.capture));accuracy.product_detection={...accuracy.capture,note:'Shopping eligibility includes sensitive-page exclusion; synthetic fixtures only'};
for(const field of ['name','price','brand','category'] as const){const eligible=predictions.filter(p=>p.truth.name);const correct=eligible.filter(p=>p.prediction.product?.[field]===p.truth[field]).length;accuracy[field]={correct,total:eligible.length,accuracy:correct/eligible.length};}
const base=extract(raw(productHtml()))!;const pairs:[Product,boolean][]=[[{...base,name:'Samsung Buds3 Pro'},true],[{...base,name:'SM-R630'},true],[{...base,model:'SM-R530'},false],[{...base,brand:'Apple',model:'AirPods'},false],[{...base,name:'갤럭시 버즈3 프로',model:''},true],[{...base,name:'Raspberry Pi 5',model:'',brand:'Raspberry Pi'},false]];
accuracy.matching=binary(pairs.map(p=>p[1]),pairs.map(p=>similarity(base,p[0])>=.85));
await mkdir('artifacts',{recursive:true});await writeFile('artifacts/ground-truth.json',JSON.stringify({description:'Hand-authored fixtures, not real-world population accuracy',cases,matching:pairs.map(([p,truth])=>({name:p.name,model:p.model,brand:p.brand,same:truth}))},null,2));
const browser=await chromium.launch({channel:'chromium',headless:true});const page=await browser.newPage({viewport:{width:1000,height:700}});const cdp=await page.context().newCDPSession(page);await cdp.send('Performance.enable');
const repetitions:Run[]=[];const stability:any[]=[];const comparison:any[]=[];const ocrChecks:any[]=[];
const fixtureSearch=async(p:Product)=>[{site:'fixture seller',status:'PASS' as const,url:'https://fixture.example/product',query:p.name,products:[{...p,price:200000,product_url:'https://fixture.example/product'}],duration_ms:0}];
const systemCpu=()=>os.cpus().reduce((s,c)=>({idle:s.idle+c.times.idle,total:s.total+Object.values(c.times).reduce((a,b)=>a+b,0)}),{idle:0,total:0});
const measure=async(fn:()=>Promise<void>)=>{const cpu=process.cpuUsage();const sys=systemCpu();const t=performance.now();const ramBefore=process.memoryUsage().rss/1048576;const samples:number[]=[];const cpuSamples:number[]=[];let previousCpu=process.cpuUsage(),previousTime=performance.now();const sample=()=>{const now=performance.now(),delta=process.cpuUsage(previousCpu);previousCpu=process.cpuUsage();cpuSamples.push((delta.user+delta.system)/1000/Math.max(1,now-previousTime)*100);previousTime=now;samples.push(process.memoryUsage().rss/1048576);};const timer=setInterval(sample,25);await fn();clearInterval(timer);sample();const used=process.cpuUsage(cpu),after=systemCpu();return {duration_ms:performance.now()-t,backend_cpu_percent:(used.user+used.system)/1000/(performance.now()-t)*100,backend_cpu_peak_percent:Math.max(...cpuSamples),system_cpu_percent:100*(1-(after.idle-sys.idle)/Math.max(1,after.total-sys.total)),ram_average_mb:samples.reduce((a,b)=>a+b,0)/samples.length,ram_peak_mb:Math.max(...samples),ram_before_mb:ramBefore,ram_after_mb:samples.at(-1)};};
try{
  const idle=await measure(async()=>{await new Promise(r=>setTimeout(r,600));});
  for(let i=0;i<100;i++){const run=createRun(raw(productHtml()));await processRun(run,{search:fixtureSearch});repetitions.push(structuredClone(run));if(i%25===24)console.log(JSON.stringify({stage:'repeat',completed:i+1,status:run.status}));}
  // Actual screenshot OCR: text exists only as rendered pixels, not in DOM product candidates.
  await page.setContent('<title>OCR pixels</title><canvas width="900" height="260"></canvas>');await page.evaluate(()=>{const c=document.querySelector('canvas')!.getContext('2d')!;c.fillStyle='white';c.fillRect(0,0,900,260);c.fillStyle='black';c.font='42px Arial';c.fillText('Galaxy Buds3 Pro',30,70);c.fillText('$259.00',30,150);});
  let image='data:image/png;base64,'+(await page.screenshot()).toString('base64');
  const ocrResources=await measure(async()=>{const result=await runOcr(image);ocrChecks.push({success:/Galaxy Buds3 Pro/i.test(result.text)&&/259/.test(result.text),text:result.text,confidence:result.confidence,preprocess_latency:result.preprocess_latency,ocr_latency:result.ocr_latency});});
  const ocrRaw=raw('<title>Product shop</title><script type="application/ld+json">{"@type":"Product"}</script>');const ocrRun=createRun(ocrRaw);await processRun(ocrRun,{image,search:fixtureSearch});stability.push({scenario:'screenshot_only_ocr_fallback',pass:ocrRun.extracted.product?.price===259,status:ocrRun.status,logs:ocrRun.logs});image='';
  const mix=[cases[0],cases[1],cases[2],cases[3],cases[5],cases[6],cases[7],cases[8],cases[10],cases[11]];
  for(const mode of ['always_capture','conditional_capture']){
    let captures=0,ocrCalls=0,sensitiveCaptures=0,unneededCaptures=0;const times:number[]=[];const captureTimes:number[]=[];const beforeMetrics=await cdp.send('Performance.getMetrics');
    const resources=await measure(async()=>{for(let i=0;i<30;i++){const f=mix[i%mix.length];await page.setContent(f.html);const r=raw(f.html,f.url);const t=performance.now();if(mode==='always_capture'||decide(r).capture){const ct=performance.now();let screenshot='data:image/png;base64,'+(await page.screenshot()).toString('base64');captureTimes.push(performance.now()-ct);captures++;if(r.signals.sensitive)sensitiveCaptures++;if(!f.shopping)unneededCaptures++;const p=extract(r);if(!p?.name||p.price===null){ocrCalls++;try{await runOcr(screenshot);}catch{/* failed OCR is counted; never crashes benchmark */}}screenshot='';}times.push(performance.now()-t);if(i%10===9)console.log(JSON.stringify({stage:mode,completed:i+1,captures,ocrCalls}));}});
    const afterMetrics=await cdp.send('Performance.getMetrics');const metric=(m:typeof afterMetrics,n:string)=>m.metrics.find(x=>x.name===n)?.value||0;
    comparison.push({mode,synthetic_only:true,runs:30,captures,ocr_calls:ocrCalls,sensitive_captures:sensitiveCaptures,unneeded_capture_ratio:unneededCaptures/30,latency:stats(times),capture_latency:stats(captureTimes),resources,browser_task_seconds:metric(afterMetrics,'TaskDuration')-metric(beforeMetrics,'TaskDuration'),browser_heap_before_mb:metric(beforeMetrics,'JSHeapUsedSize')/1048576,browser_heap_after_mb:metric(afterMetrics,'JSHeapUsedSize')/1048576});
  }
  // Failure injection and real browser conditions are identified separately.
  for(const scenario of ['normal_network','slow_network','network_offline','site_delay','empty_page','non_product','ocr_failure','no_search_results','invalid_price','timeout','external_block','capture_failure']){
    const run=createRun(raw(scenario==='empty_page'?'':scenario==='non_product'?'<h1>News</h1>':scenario==='invalid_price'?productHtml('Samsung Galaxy Buds3 Pro',-1):productHtml()));
    await processRun(run,{capture_error:scenario==='capture_failure'?'CAPTURE_FAILED':undefined,image:scenario==='ocr_failure'?'data:image/png;base64,bm90YW5pbWFnZQ==':undefined,search:async(p)=>{if(['slow_network','site_delay'].includes(scenario))await new Promise(r=>setTimeout(r,150));if(scenario==='network_offline')throw Error('NETWORK_OFFLINE');if(scenario==='timeout')throw Error('TimeoutError');if(scenario==='external_block')return [{site:'fixture',status:'BLOCKED',url:'https://fixture.example',query:p.name,products:[],error:'HTTP_403',duration_ms:0}];return scenario==='no_search_results'?[]:fixtureSearch(p);}});
    const expected=['empty_page','non_product'].includes(scenario)?'skipped':['network_offline','timeout'].includes(scenario)?'error':['external_block','no_search_results'].includes(scenario)?'complete_no_results':'complete';
    stability.push({scenario,kind:'controlled injection',pass:run.status===expected,status:run.status,expected,logs:run.logs.filter(l=>!l.success)});
  }
  await page.setContent('<title>SPA fixture</title><main id="p"></main>');await page.evaluate(()=>{history.pushState({},'','#new-product');document.getElementById('p')!.innerHTML='<h1>Raspberry Pi 5</h1><b class="price">£80.00</b><button>Add to cart</button>';});const dynamic=raw(await page.content());stability.push({scenario:'dynamic_dom_and_spa',kind:'real browser DOM mutation',pass:extract(dynamic)?.price===80});
  await page.evaluate(()=>{for(let i=0;i<500;i++){const p=document.createElement('p');p.textContent='placeholder';document.body.append(p);}});const infinite=raw(await page.content());stability.push({scenario:'infinite_scroll_like_dom_growth',kind:'synthetic 500 nodes',pass:JSON.stringify(infinite).length<10000});
  const token=(await readFile('artifacts/server-token.txt','utf8')).trim();const auth={Authorization:`Bearer ${token}`};
  for(const [name,init,expected] of [['missing_token',{},401],['non_ascii_token',{headers:{Authorization:'Bearer '+'ÿ'.repeat(64)}},401],['hostile_origin',{headers:{...auth,Origin:'https://evil.example'}},403],['invalid_payload',{method:'POST',headers:{...auth,'Content-Type':'application/json'},body:'{}'},400]] as const){const url='http://127.0.0.1:8787/'+(name==='invalid_payload'?'analyze':'runs');const res=await fetch(url,init);stability.push({scenario:name,kind:'real HTTP',pass:res.status===expected,status:res.status});}
  try{await fetch('http://127.0.0.1:8799/health',{signal:AbortSignal.timeout(1000)});stability.push({scenario:'backend_down',pass:false});}catch{stability.push({scenario:'backend_down',kind:'real connection refused',pass:true});}
  const stages=Object.keys(repetitions[0].timings);const timing=Object.fromEntries(stages.map(s=>[s,stats(repetitions.map(r=>r.timings[s]))]));
  const output={timestamp:new Date().toISOString(),environment:{os:`${os.type()} ${os.release()}`,cpu:os.cpus()[0].model,logical_cpus:os.cpus().length,ram_gb:os.totalmem()/1073741824,node:process.version,python:'not installed / not used',browser:browser.version()},scope:'100 deterministic backend pipelines with fixture search; 30 + 30 actual browser capture/OCR benchmark runs; live E2E separately',repeated:{runs:100,success:repetitions.filter(r=>r.status==='complete').length,failed:repetitions.filter(r=>r.status!=='complete').length,crashes:0,timeouts:0,latency:timing,memory_growth_mb:Number(repetitions.at(-1)?.resources.ram_peak_mb)-Number(repetitions[0].resources.ram_peak_mb),first_ten_latency:stats(repetitions.slice(0,10).map(r=>r.timings.total_latency)),last_ten_latency:stats(repetitions.slice(-10).map(r=>r.timings.total_latency)),cpu_average_percent:stats(repetitions.map(r=>Number(r.resources.cpu_average_percent))),ram_peak_mb:Math.max(...repetitions.map(r=>Number(r.resources.ram_peak_mb)))},capture_comparison:comparison,ocr:{checks:ocrChecks,resources:ocrResources},idle,gpu:{status:'NOT_MEASURED'},browser_memory_scope:'JS heap only; not complete browser process RSS'};
  await writeFile('BENCHMARK_RESULTS.json',JSON.stringify(output,null,2));await writeFile('TEST_RESULTS.json',JSON.stringify({timestamp:new Date().toISOString(),accuracy,stability,repeat:output.repeated,ocr:ocrChecks,fixture_count:cases.length},null,2));console.log(JSON.stringify({stage:'complete',repeats:100,stability_pass:stability.filter(s=>s.pass).length,stability_total:stability.length,ocr:ocrChecks[0]?.success}));
  if(stability.some(s=>!s.pass)||ocrChecks.some(s=>!s.success)||repetitions.some(r=>r.status!=='complete'))process.exitCode=1;
}finally{eraseAll();await browser.close();}
